package billsplit.pma.hdm.de.billsplit;

import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.preference.PreferenceManager;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.TypedValue;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import java.util.ArrayList;
import static java.lang.Float.parseFloat;

public class OverviewActivity extends AppCompatActivity {

    ArrayList<String> names = new ArrayList<String>();
    ArrayList<String> whoAteWhat = new ArrayList<String>();
    String shareText = "Hey, hier kannst du sehen was wir gegessen haben:";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_overview);

        LinearLayout lLayout = (LinearLayout) findViewById(R.id.overviewLinLayout);
        LinearLayout.LayoutParams overParams = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        overParams.setMargins(20, 20, 20, 20);

        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);

        int nameArrSize = prefs.getInt("nameCount", 0);
        int foodArrSize = prefs.getInt("foodArr", 0);

        //create a TextView for every consumer
        for (int i=0; i<nameArrSize; i++) {
            names.add(prefs.getString("name_" + i, null));
            String whoIsThis = names.get(i);

            TextView overView = new TextView(getApplicationContext());
            overView.setLayoutParams(overParams);
            overView.setText(names.get(i) + "\n___________________\n");

            Float price = 0.0f;

            //loop through the selected meals
            for (int z=0; z<foodArrSize; z++) {
                whoAteWhat.add(prefs.getString("whoAteWhat_" + z, null));
                String whoFoodPrice = whoAteWhat.get(z);
                String[] splitWhoFoodPrice = whoFoodPrice.split("---");
                String who = splitWhoFoodPrice[0];

                //add meal and price to specific consumer
                if (whoIsThis.equals(who)) {
                    String currentText = overView.getText().toString();
                    String newText = currentText + "\n   " + splitWhoFoodPrice[1] + " - " + splitWhoFoodPrice[2];
                    overView.setText(newText);
                    String priceFood = splitWhoFoodPrice[2];
                    priceFood = priceFood.substring(0, priceFood.length()-1);
                    priceFood = priceFood.replace(",", ".");
                    Float pFood = parseFloat(priceFood);
                    price = price + pFood;
                }
            }

            //formatting
            String currentText = overView.getText().toString();
            String newText = currentText + "\n   ________________\n   Summe : " + String.format("%.2f", price) + "€\n";
            overView.setText(newText);
            overView.setTextColor(Color.parseColor("#FFFFFF"));
            float textSize = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 6.5F, getResources().getDisplayMetrics());
            overView.setTextSize(textSize);
            overView.setBackground( getResources().getDrawable(R.drawable.round_textview));

            //setting String for Share-Output
            shareText = shareText + "\n\n" + newText;

            lLayout.addView(overView, i);
        }

        shareText = shareText + "\n\nautomatically generated by BillSplit";

        //Share-Output
        Button shareButton = (Button) findViewById(R.id.shareButton);
        shareButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent shareIntent = new Intent(Intent.ACTION_SEND);
                shareIntent.setType("text/plain");
                shareIntent.putExtra(Intent.EXTRA_TEXT, shareText);
                startActivity(Intent.createChooser(shareIntent, "Mitteilen über:"));

            }
        });
    }
}
